<a href="https://colab.research.google.com/github/Roborueslbff/SpOoNs/blob/main/Colab_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import numpy as np

# Tensors

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
# Reshape if we dont know the number of items using -1
my_torch2 = torch.arange(18)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [20]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])

In [21]:
# slices
my_torch4 = torch.arange(10)
my_torch4[7]

tensor(7)

In [22]:
# grab slice
my_torch5 = my_torch4.reshape(5,2)
my_torch5

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
my_torch5[:,1]

tensor([1, 3, 5, 7, 9])

In [24]:
# return column
my_torch5[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [27]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [28]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [30]:
# subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])